author: "Farzaneh"
date: "02/24/2023"
output: html_document
---



```{r}
### Assignment #2  LA-558   Farzaneh-Faramarzi
### Farzaneh Faramarzi
### Professor Seeger
library(ggplot2)
library(dplyr)
library(maptools)
library(tidyverse)
library(maps)
library(mapdata)
```


```{r}
# Map 1

#install.packages(c("gpclib","maptools"))
library("gpclib")
setwd("C:/Spring 2023/CRP 558/LA-558/GisData/London")
London_shp = readShapePoly("LDNSuicides.shp")
London_csv<-read.csv("london.csv")
plot(London_shp)
View(London_csv)
max(London_csv$E)
count(London_csv)

London_shp$ID1=row.names(London_shp)
London_csv$ID2=row.names(London_csv)
shp.csv=merge(London_shp, London_csv, by.x = "ID1", by.y = "ID2")
s = spplot(shp.csv, zcol="logSMR",col=NA,main="London Map - Boroughs of the London")
s
```

```{r}
# Map 2
setwd("C:/Spring 2023/CRP 558/LA-558/GisData")
Ames <- read.csv("Ameshousing.csv")
View(Ames)
head(Ames)
summarize(Ames)
##number of houses
dim(Ames)
#or
nrow(Ames)

##names of variables
str(Ames) 
#or 
colnames(Ames)
#or
names(Ames)

## some statistics
meanarea <- mean(Ames$LivingArea)
meanarea

stdarea <- sd(Ames$LivingArea)
stdarea

medarea <- median(Ames$LivingArea)
medarea

mean(Ames$SalePrice)
sd(Ames$SalePrice/sqrt(length(Ames$SalePrice)))

## Mapping
library(ggplot2)
f = ggplot(Ames, aes(x = LivingArea,  y = SalePrice))+
  geom_point(col="green", size = 4)+
  geom_smooth(col="red", width=0.5)+
  labs(x = "Living Area", y = "House Sale Price", title = "House Sale Price vs Living Area" )
f
f + coord_flip()
```
